// jwt-tool-app/frontend/components/ui/TabsTrigger.tsx
'use client'

import { useTabs } from './Tabs'

interface TabsTriggerProps {
    value: string
    children: React.ReactNode
}

export default function TabsTrigger({ value, children }: TabsTriggerProps) {
    const { activeTab, setActiveTab } = useTabs()
    const isActive = activeTab === value

    return (
        <button
            onClick={() => setActiveTab(value)}
            className={isActive ? 'active' : ''}
        >
            {children}
            <style jsx>{`
        button {
          padding: 0.5rem 1rem;
          border: none;
          background: none;
          cursor: pointer;
          font-weight: 600;
          color: var(--color-muted-foreground);
          border-bottom: 2px solid transparent;
          transition: all 0.2s;
        }

        button:hover {
          color: var(--color-foreground);
        }

        button.active {
          color: var(--color-primary);
          border-bottom-color: var(--color-primary);
        }
      `}</style>
        </button>
    )
}

// jwt-tool-app/frontend/src/lib/components/ui/tabs-trigger.svelte
<script lang="ts">
	import { getContext } from 'svelte';
	import type { Writable } from 'svelte/store';

	export let value: string;

	const { activeTab, setActiveTab } = getContext<{
		activeTab: Writable<string>;
		setActiveTab: (value: string) => void;
	}>('tabs');

	$: isActive = $activeTab === value;
</script>

<button class="tab-trigger" class:active={isActive} on:click={() => setActiveTab(value)}>
	<slot />
</button>

<style>
	.tab-trigger {
		padding: var(--spacing-sm) var(--spacing-lg);
		background: transparent;
		border: none;
		border-bottom: 2px solid transparent;
		cursor: pointer;
		font-weight: 600;
		color: var(--color-muted-foreground);
		transition: all 0.2s;
		font-family: var(--font-sans);
		font-size: 1rem;
	}

	.tab-trigger:hover {
		color: var(--color-foreground);
	}

	.tab-trigger.active {
		color: var(--color-foreground);
		border-bottom-color: var(--color-primary);
	}
</style>
