// jwt-tool-app/frontend/src/lib/components/ui/button.svelte
<script lang="ts">
	export let variant: 'default' | 'outline' | 'ghost' = 'default';
	export let size: 'sm' | 'md' | 'lg' = 'md';
	export let disabled = false;
	export let type: 'button' | 'submit' | 'reset' = 'button';
</script>

<button {type} class="btn btn-{variant} btn-{size}" {disabled} on:click>
	<slot />
</button>

<style>
	.btn {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		gap: var(--spacing-xs);
		font-weight: 600;
		border-radius: var(--radius-md);
		transition: all 0.2s;
		cursor: pointer;
		border: none;
		font-family: var(--font-sans);
	}

	.btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	/* Variants */
	.btn-default {
		background-color: var(--color-primary);
		color: var(--color-primary-foreground);
	}

	.btn-default:hover:not(:disabled) {
		opacity: 0.9;
	}

	.btn-outline {
		background-color: transparent;
		border: 2px solid var(--color-border);
		color: var(--color-foreground);
	}

	.btn-outline:hover:not(:disabled) {
		background-color: var(--color-accent);
	}

	.btn-ghost {
		background-color: transparent;
		color: var(--color-foreground);
	}

	.btn-ghost:hover:not(:disabled) {
		background-color: var(--color-accent);
	}

	/* Sizes */
	.btn-sm {
		padding: var(--spacing-xs) var(--spacing-md);
		font-size: 0.875rem;
	}

	.btn-md {
		padding: var(--spacing-sm) var(--spacing-lg);
		font-size: 1rem;
	}

	.btn-lg {
		padding: var(--spacing-md) var(--spacing-xl);
		font-size: 1.125rem;
	}
</style>

// pudra-expriment/frontend/components/ui/button.tsx
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

const buttonVariants = cva(
    "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50",
    {
        variants: {
            variant: {
                default:
                    "bg-primary text-primary-foreground shadow hover:bg-primary/90",
                destructive:
                    "bg-destructive text-destructive-foreground shadow-sm hover:bg-destructive/90",
                outline:
                    "border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground",
                secondary:
                    "bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80",
                ghost: "hover:bg-accent hover:text-accent-foreground",
                link: "text-primary underline-offset-4 hover:underline",
            },
            size: {
                default: "h-9 px-4 py-2",
                sm: "h-8 rounded-md px-3 text-xs",
                lg: "h-10 rounded-md px-8",
                icon: "h-9 w-9",
            },
        },
        defaultVariants: {
            variant: "default",
            size: "default",
        },
    }
);

export interface ButtonProps
    extends React.ButtonHTMLAttributes<HTMLButtonElement>,
        VariantProps<typeof buttonVariants> {
    asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
    ({ className, variant, size, ...props }, ref) => {
        return (
            <button
                className={cn(buttonVariants({ variant, size, className }))}
                ref={ref}
                {...props}
            />
        );
    }
);
Button.displayName = "Button";

export { Button, buttonVariants };
